In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
train_df = pd.read_excel("Data_Train.xlsx")
train_df.sample(3)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10035,IndiGo,6/04/2019,Banglore,Delhi,BLR → DEL,10:10,13:00,2h 50m,non-stop,No info,4423
10008,IndiGo,9/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,21:00,9h 35m,1 stop,No info,6979
838,Jet Airways,18/05/2019,Delhi,Cochin,DEL → BOM → COK,22:50,19:00 19 May,20h 10m,1 stop,No info,15554

In [3]:
test_df = pd.read_excel("Test_set.xlsx")
test_df.sample(3)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
2103,Multiple carriers,27/03/2019,Delhi,Cochin,DEL → BOM → COK,12:50,01:35 28 Mar,12h 45m,1 stop,No info
990,Jet Airways,15/06/2019,Banglore,Delhi,BLR → DEL,07:10,10:10,3h,non-stop,No info
682,IndiGo,12/06/2019,Kolkata,Banglore,CCU → BBI → BLR,19:35,23:15,3h 40m,1 stop,No info

In [4]:
df = pd.concat([train_df,test_df])
df.sample(3)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
900,IndiGo,9/05/2019,Banglore,Delhi,BLR → DEL,22:10,01:00 10 May,2h 50m,non-stop,No info,NaN
2009,Jet Airways,24/03/2019,Kolkata,Banglore,CCU → BOM → BLR,16:55,20:40 25 Mar,27h 45m,1 stop,In-flight meal not included,NaN
3457,Air India,6/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,07:05,19:15 07 Mar,36h 10m,2 stops,No info,11552.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.2+ MB

In [6]:
df.isnull().sum()

Airline               0
Date_of_Journey       0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
dtype: int64

In [7]:
df.loc[df["Route"].isnull()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480.0

In [8]:
df = df.dropna(subset=["Route"])

Feature Engineering Process

In [9]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"])

In [10]:
df["Day"] = df["Date_of_Journey"].dt.day
df["Month"] = df["Date_of_Journey"].dt.month
df["Year"] = df["Date_of_Journey"].dt.year

In [11]:
df.drop(columns=["Date_of_Journey"],axis=1,inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13353 entries, 0 to 2670
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13353 non-null  object
 1   Source           13353 non-null  object
 2   Destination      13353 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13353 non-null  object
 5   Arrival_Time     13353 non-null  object
 6   Duration         13353 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13353 non-null  object
 9   Price            10682 non-null  float64
 10  Day              13353 non-null  int32
 11  Month            13353 non-null  int32
 12  Year             13353 non-null  int32
dtypes: float64(1), int32(3), object(9)
memory usage: 1.3+ MB

In [13]:
df["Arrival_Time"] = df["Arrival_Time"].str.split(" ").str[0]

In [14]:
df["Arrival_Hour"] = df["Arrival_Time"].str.split(":").str[0]
df["Arrival_Min"] = df["Arrival_Time"].str.split(":").str[1]

In [15]:
df["Dep_Hour"] = df["Dep_Time"].str.split(":").str[0]
df["Dep_Min"] = df["Dep_Time"].str.split(":").str[1]

In [16]:
df["Arrival_Hour"] = df["Arrival_Hour"].astype(int)
df["Dep_Min"] = df["Arrival_Min"].astype(int)

In [17]:
df["Dep_Hour"] = df["Dep_Hour"].astype(int)
df["Dep_Min"] = df["Dep_Min"].astype(int)

In [18]:
df.drop(columns=["Dep_Time","Arrival_Time"],inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13353 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13353 non-null  object
 1   Source           13353 non-null  object
 2   Destination      13353 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13353 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13353 non-null  object
 7   Price            10682 non-null  float64
 8   Day              13353 non-null  int32
 9   Month            13353 non-null  int32
 10  Year             13353 non-null  int32
 11  Arrival_Hour     13353 non-null  int32
 12  Arrival_Min      13353 non-null  object
 13  Dep_Hour         13353 non-null  int32
 14  Dep_Min          13353 non-null  int32
dtypes: float64(1), int32(6), object(8)
memory usage: 1.3+ MB

In [20]:
df.head(3)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25

In [21]:
df["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [22]:
df["Total_Stops"] = df["Total_Stops"].map({"non-stop":0, "1 stop":1 ,"2 stops":2, "3 stops": 3, "4 stops": 4})

In [24]:
df["Total_Stops"] = df["Total_Stops"].astype(int)

In [25]:
df.drop(columns="Route",axis=True,inplace=True)

In [26]:
df.head(3)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,10
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,15
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882.0,9,6,2019,4,25,9,25

In [27]:
df[df["Duration"]=="5m"]

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
6474,Air India,Mumbai,Hyderabad,5m,2,No info,17327.0,6,3,2019,16,55,16,55
2660,Air India,Mumbai,Hyderabad,5m,2,No info,NaN,12,3,2019,16,55,16,55

In [28]:
df = df.drop(df.loc[df["Duration"] == "5m"].index)

In [29]:
df["Dur_Hour"] = df["Duration"].str.split(" ").str[0].str.split("h").str[0]
df["Dur_Min"] = df["Duration"].str.split(" ").str[1].str.split("m").str[0]

In [30]:
df.drop(columns="Duration",axis=1,inplace=True)

In [31]:
df["Dur_Min"] = df["Dur_Min"].fillna("0")

In [32]:
df["Duration"] = df["Dur_Hour"].astype(int)*60 + df["Dur_Min"].astype(int)

In [33]:
df.drop(columns=["Dur_Hour","Dur_Min"],axis=1,inplace=True)

In [34]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Duration
0,IndiGo,Banglore,New Delhi,0,No info,3897.0,24,3,2019,1,10,22,10,170
1,Air India,Kolkata,Banglore,2,No info,7662.0,1,5,2019,13,15,5,15,445
2,Jet Airways,Delhi,Cochin,2,No info,13882.0,9,6,2019,4,25,9,25,1140
3,IndiGo,Kolkata,Banglore,1,No info,6218.0,12,5,2019,23,30,18,30,325
4,IndiGo,Banglore,New Delhi,1,No info,13302.0,1,3,2019,21,35,16,35,285

In [35]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
for col in df.columns:
    if df[col].dtype==object:
        df[col] = label.fit_transform(df[col])

In [36]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,Duration
0,3,0,5,0,8,3897.0,24,3,2019,1,2,22,10,170
1,1,3,0,2,8,7662.0,1,5,2019,13,3,5,15,445
2,4,2,1,2,8,13882.0,9,6,2019,4,5,9,25,1140
3,3,3,0,1,8,6218.0,12,5,2019,23,6,18,30,325
4,3,0,5,1,8,13302.0,1,3,2019,21,7,16,35,285

In [37]:
df_test = df[df['Price'].isnull()]
df_train = df[df['Price'].notnull()]

In [39]:
x_test = df_test.drop(['Price'],axis = 1)
x_train = df_train.drop(['Price'],axis = 1)
y_train = df_train["Price"]

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor

# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, confusion_matrix

In [42]:
models = {"Linear_reg" : LinearRegression(),
"KNN" : KNeighborsRegressor(),
"Desi_tree" : DecisionTreeRegressor(),
"R_forest" : RandomForestRegressor(n_estimators=50),
"AdaBoost" : AdaBoostRegressor(),
"Gradient Boosting" : GradientBoostingRegressor()
         }

In [43]:
from sklearn.model_selection import cross_validate
from joblib import parallel_backend

In [44]:
best_model = None
best_score = -np.inf

with parallel_backend('loky'):
    for name, model in models.items():
        results = cross_validate(model, x_train_scaled, y_train, scoring='r2', cv=3, return_estimator=True)  # Save model

        mean_score = np.mean(results['test_score'])  # Mean R² score

        print(f"{name}: Mean R² = {mean_score:.4f}, Std Dev = {np.std(results['test_score']):.4f}")

        # Step 2: Keep the best model
        if mean_score > best_score:
            best_score = mean_score
            best_model = results['estimator'][0]  # Store the first trained model from cross-validation

print("\nBest Model Selected:", best_model)

Linear_reg: Mean R² = 0.4321, Std Dev = 0.0127
KNN: Mean R² = 0.7556, Std Dev = 0.0038
Desi_tree: Mean R² = 0.7747, Std Dev = 0.0054
R_forest: Mean R² = 0.8522, Std Dev = 0.0202
AdaBoost: Mean R² = 0.3212, Std Dev = 0.1016
Gradient Boosting: Mean R² = 0.8096, Std Dev = 0.0138

Best Model Selected: RandomForestRegressor(n_estimators=50)

In [45]:
# by this conclusion Random Forest Regressor is the best model

In [51]:
y_pred = best_model.predict(x_test_scaled)
print("Predictions:", y_pred)

Predictions: [14714.    4282.78 12898.   ... 15800.66 12737.04  7786.6 ]

In [53]:
prediction = pd.DataFrame(y_pred,columns=["Prdection"])

In [54]:
prediction

      Prdection
0     14714.000
1      4282.780
2     12898.000
3     11303.166
4      3418.960
...         ...
2665  10225.180
2666   4814.320
2667  15800.660
2668  12737.040
2669   7786.600

[2670 rows x 1 columns]